--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "esMX");
if ( not L ) then 
    return;
end

-- GuildBank
L["ARMORY_CMD_DELETE_GUILD"] = "Banco de la Hermandad"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Banco de la Hermandad de '%1$s' en el reino '%2$s' ha sido removido."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Banco de la Hermandad de '%1$s'en el reino '%2$s' no ha sido encontrado!"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = " [hermandad] [reino] "
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "Borrar Banco de Hermandad"
L["ARMORY_CMD_GUILDBANK"] = "Banco de Hermandad|bh"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Ocultar Banco de Hermandad"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "Alterna el Banco de Hermandad habilitado o deshabilitado"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Incluir todos los reinos en la cuenta"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "Incluye cuenta de objeto para todos los reinos"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "Si esta habilitado, los totales en el banco de hermandad se muestra para todos los reinos; de otra manera solo para el reino actual."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "If enabled, Guild Bank totals are shown for the current and selected character's guild only."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_MENUTEXT"] = "Include personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TEXT"] = "include item counts for personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TOOLTIP"] = "If enabled, Guild Banks totals are shown for personal guilds only."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all factions; otherwise only for the current faction."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "incluir en '/ar buscar objeto|todos'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "Incluir cuando se buscas objetos"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "If enabled, the Guild Bank will also be searched when performing a database lookup with '/ar find item|all'."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "If enabled, the selected character's Guild Bank will be added as an extra tab in the inventory sheet."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Show tooltip item counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "show item counts in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "If enabled, item tooltips will show Guild Bank totals."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Use Armory's color"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "link to Armory's item count color"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "If enabled, the same color will be used for all item counts shown in tooltips."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_ABORTING"] = "Aborting..."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_NO_DATA"] = "There is no Guild Bank data available."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_NO_TABS"] = "Please visit the bank and open all tabs..."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_SUBTEXT"] = "These options allow you to modify Armory Guild Bank's behavior."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_TITLE"] = "Guild Bank"
--[[Translation missing --]]
L["ARMORY_PERSONAL"] = "Personal"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK"] = "Personal Guild Bank"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK_TOOLTIP"] = "If enabled, guild bank gold will be included in character gold totals."
--[[Translation missing --]]
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Toggle Armory Guild Bank"

