--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.

    Original translators: MegaKSVS, alex_n
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "ruRU");
if ( not L ) then 
    return;
end

-- GuildBank
L["ARMORY_CMD_DELETE_GUILD"] = "гб"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Гильд Банк '%1$s' на сервере '%2$s' удален."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Гильд Банк '%1$s' на сервере '%2$s' не найден!"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[гильдия] [сервер]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "удалить гильд банк"
L["ARMORY_CMD_GUILDBANK"] = "гильдбанк|гб"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Включить/выключить Гильд Банк"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "включает/выключает Гильд Банк"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Включить все сервера в счет"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "включить счет вещей для всех серверов"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "Если включено, Тотал Гильд Банка будет показоватся для всех серверов; в ином случае только для данного сервера."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "If enabled, Guild Bank totals are shown for the current and selected character's guild only."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_MENUTEXT"] = "Include personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TEXT"] = "include item counts for personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TOOLTIP"] = "If enabled, Guild Banks totals are shown for personal guilds only."
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Включать все фракции в подсчет"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "включать подсчет количества предметов для всех фракций"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "Если включено, итоговое количество для ГильдБанка будет показано для всех фракций, иначе -  только для текущей фракции."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "Включить в '/ar find item|all'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "включить при поиске вещей"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "Если включено, Гильд Банк будет также просмотрен когда вы включаете просмотр базы данных  с '/ar find item|all'."
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Интегрировать с инвентарем"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "интегрирование с инвентарем Армори"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "Если включено, Гильд Банк выбраного персонажа будет добавлен как дополнительный слот в инвентаре."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Показывать счет вещей в подсказке"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "показать счет вещей в подсказке"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "Если включено, подсказка будет показовать полную инфу о Гильд Банке."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Использовать цвет Армори"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "ссылка на подсчет вещей Армори"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "Если включено, тот же цвет для всех вещей будет использован в подсказке."
L["ARMORY_GUILDBANK_ABORTING"] = "Отмена..."
L["ARMORY_GUILDBANK_NO_DATA"] = "Данные по Гильд Банку не доступны."
L["ARMORY_GUILDBANK_NO_TABS"] = "Пожалуйста посетите банк и откройте все слоты..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "Эти настройки позволяют модифицировать поведение Гильд Банка в Армори."
L["ARMORY_GUILDBANK_TITLE"] = "Гильд Банк"
--[[Translation missing --]]
L["ARMORY_PERSONAL"] = "Personal"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK"] = "Personal Guild Bank"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK_TOOLTIP"] = "If enabled, guild bank gold will be included in character gold totals."
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Показать\\скрыть банк гильдий Armory"

