--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "zhCN");
if ( not L ) then 
    return;
end

-- GuildBank
L["ARMORY_CMD_DELETE_GUILD"] = "公会银行"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "'%2$s'服务器的'%1$s'公会银行已被移除。"
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "没有找到%2$s'服务器的'%1$s'公会银行。"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[公会] [服务器]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "删除公会银行"
L["ARMORY_CMD_GUILDBANK"] = "公会银行"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "开关Guild Bank"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "开关Guild Bank"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "包括所有服务器计数"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "包括所有服务器的物品计数"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "如果启用，将显示所有服务器的公会银行总计; 否则只针对当前服务器。"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "仅包含当前公会"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "仅包含当前公会的物品计数"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "如果启用，则仅显示当前和所选角色的公会的公会银行总计。"
L["ARMORY_CMD_SET_AGBCOUNTPGB_MENUTEXT"] = "仅包括私人公会"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TEXT"] = "include item counts for personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TOOLTIP"] = "If enabled, Guild Banks totals are shown for personal guilds only."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all factions; otherwise only for the current faction."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "包含在 '/ar find item|all'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "搜索物品时包含在内"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "如果打开此功能, 当使用 '/ar find item|all' 命令搜索数据库时将包含公会银行."
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "If enabled, the selected character's Guild Bank will be added as an extra tab in the inventory sheet."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "在信息提示中显示物品数量"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "在信息提示中显示物品数量"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "如果打开此功能, 物品提示信息中将显示在公会银行中的数量."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "使用 Armory 的颜色"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "链接到 Armory 的物品数字颜色"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "I如果打开此功能, 所有物品数量使用同一个颜色."
L["ARMORY_GUILDBANK_ABORTING"] = "中断..."
L["ARMORY_GUILDBANK_NO_DATA"] = "没有可用的公会银行数据."
L["ARMORY_GUILDBANK_NO_TABS"] = "请查看银行并打开所有标签..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "设置Armory Guild Bank"
L["ARMORY_GUILDBANK_TITLE"] = "公会银行"
--[[Translation missing --]]
L["ARMORY_PERSONAL"] = "Personal"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK"] = "Personal Guild Bank"
L["ARMORY_PERSONAL_GUILDBANK_TOOLTIP"] = "如果启用，公会银行金币将包含在角色金币总计中。"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "开关Armory Guild Bank"

