--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "zhTW");
if ( not L ) then 
    return;
end

-- GuildBank
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_GUILD"] = "gb"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "'%2$s' 伺服器中的 '%1$s' 公會銀行已被刪除。"
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "找不到 '%2$s' 伺服器中的 '%1$s' 公會銀行。"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[公會] [伺服器]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "刪除公會銀行"
L["ARMORY_CMD_GUILDBANK"] = "公會銀行|gb"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "切換公會銀行"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "切換打開/關閉公會銀行"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "包含所有伺服器"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "include item counts for all realms"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "如果啟用，則顯示所有伺服器的公會銀行總計； 否則僅適用於目前伺服器。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "如果啟用，則僅對目前角色和所選角色公會顯示公會銀行總計。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_MENUTEXT"] = "Include personal guilds only"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTPGB_TEXT"] = "include item counts for personal guilds only"
L["ARMORY_CMD_SET_AGBCOUNTPGB_TOOLTIP"] = "如果啟用，則僅針對個人公會顯示公會銀行總計。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "如果啟用，將顯示所有陣營的公會行銀行總計； 否則僅適用於當前陣營。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "Include in '/ar find item|all'"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "include when searching for items"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "如果啟用，則在使用 '/ ar find item | all' 執行搜尋資料庫時，還將搜索公會銀行。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "如果啟用，所選角色的公會銀行將作為附加頁添加到清單中。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Show tooltip item counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "show item counts in tooltips"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "如果啟用，項目工具提示將顯示公會銀行總計。"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Use Armory's color"
--[[Translation missing --]]
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "link to Armory's item count color"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "如果啟用，工具提示中顯示的所有項目計數將使用相同的顏色。"
--[[Translation missing --]]
L["ARMORY_GUILDBANK_ABORTING"] = "Aborting..."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_NO_DATA"] = "There is no Guild Bank data available."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_NO_TABS"] = "Please visit the bank and open all tabs..."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_SUBTEXT"] = "These options allow you to modify Armory Guild Bank's behavior."
--[[Translation missing --]]
L["ARMORY_GUILDBANK_TITLE"] = "Guild Bank"
--[[Translation missing --]]
L["ARMORY_PERSONAL"] = "Personal"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK"] = "Personal Guild Bank"
--[[Translation missing --]]
L["ARMORY_PERSONAL_GUILDBANK_TOOLTIP"] = "If enabled, guild bank gold will be included in character gold totals."
--[[Translation missing --]]
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Toggle Armory Guild Bank"

